### ISSUE TITLE
.

### ISSUE THREAD

**Issue by naveenhax** [konichar/engagmentpushbot#1]

**Comment by konichar** [comment]
Thanks for reaching out. I would be updating the Readme.MD file in some days you can put this repo on your watched list so you would know whenever there is an updated version of the code and documentation. However, if you would like me for me to personally set up this project for your specific business environment and twerk it to your liking please contact me privately at richardokonicha@gmail.com.

**Comment by Marvel-exe** [comment]
For setting it up personally uh charge money?🤔

**Comment by konichar** [comment]
Yes Sir, I would do the setup as well as other modification to fit your
business need.

**Comment by konichar** [comment]
However, If you're low on budget please exercise a little patience, I have
gotten many requests to modify the readme to help people utilize the
project and I will be updating the documentation.

**Comment by richardokonicha** [comment]
You can now follow through with the Readme and do a local setup.
To deploy on heroku you only need to point your fork to heroku

**Comment by Marsic1** [comment]
> You can now follow through with the Readme and do a local setup.
> To deploy on heroku you only need to point your fork to heroku

i did fork the project and edited the .env, but for some reason the bot seems to be in german and keeps crashing on heroku with the error "Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch"
do you have any idea on what could be the issue? i've set debug to False
